changelog:
  categories:
    - title: New Features
      labels:
        - feat
    - title: Bug Fixes
      labels:
        - fix
    - title: Workflow Changes
      labels:
        - workflow
    - title: Test Updates
      labels:
        - test
    - title: Documentation
      labels:
        - docs
    - title: Performance Improvements
      labels:
        - perf
    - title: Refactor
      labels:
        - refactor
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependency Updates
      labels:
        - dependencies
